// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFeedback2.Models;

namespace WebFeedback2.Migrations
{
    [DbContext(typeof(UserDetailContext))]
    [Migration("20190128184621_InitialDetail2")]
    partial class InitialDetail2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebFeedback2.Models.MessageDetail", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("MessageID");

                    b.ToTable("MessageDetail");
                });

            modelBuilder.Entity("WebFeedback2.Models.ThemeDetail", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TextTheme")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ThemeID");

                    b.ToTable("ThemeDetail");
                });

            modelBuilder.Entity("WebFeedback2.Models.UserDetail", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDMessage")
                        .HasColumnType("int");

                    b.Property<int>("IDTheme");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("UserNumPhone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("UserID");

                    b.ToTable("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
